# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VGVI_cpp <- function(dsm, dsm_values, greenspace, greenspace_values, x0, y0, radius, h0, fun, m, b) {
    .Call(`_GVI_VGVI_cpp`, dsm, dsm_values, greenspace, greenspace_values, x0, y0, radius, h0, fun, m, b)
}

VGVI_cpp2 <- function(dsm, dsm_values, greenspace, greenspace_values, x0, y0, radius, h0, fun, m, b, ncores = 1L) {
    .Call(`_GVI_VGVI_cpp2`, dsm, dsm_values, greenspace, greenspace_values, x0, y0, radius, h0, fun, m, b, ncores)
}

viewshed_cpp <- function(dsm, dsm_values, x0, y0, radius, h0) {
    .Call(`_GVI_viewshed_cpp`, dsm, dsm_values, x0, y0, radius, h0)
}

